spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/teatro_loreto"
    username: "root"
    password: "Trucebaldanzi35"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true